"""Added SensorTrainingData model

Revision ID: 520eeb58cd8d
Revises: 92ccc2be73f7
Create Date: 2026-02-19 11:17:56.317993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520eeb58cd8d'
down_revision = '92ccc2be73f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_training_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('sensor_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_training_data')
    # ### end Alembic commands ###
