"""Added MLModel table

Revision ID: 6ae25ed0c87d
Revises: 520eeb58cd8d
Create Date: 2026-02-19 11:36:43.753411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae25ed0c87d'
down_revision = '520eeb58cd8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ml_models')
    # ### end Alembic commands ###
